// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwvlyubqpdspoblnmtim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dmx5dWJxcGRzcG9ibG5tdGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzkwMjUsImV4cCI6MjA2MjI1NTAyNX0.anxR9QJflKKAmq1m50bhBtQpUocKadK3I0AfRTaTdNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);